### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by longware** [Tenpi/Photo-Viewer#1]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Program Files\Photo Viewer\resources\app.asar\node_modules\sharp\lib\sharp.js
- C:\Program Files\Photo Viewer\resources\app.asar\node_modules\sharp\lib\constructor.js
- C:\Program Files\Photo Viewer\resources\app.asar\node_modules\sharp\lib\index.js
- C:\Program Files\Photo Viewer\resources\app.asar\dist\main.js
- 

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Program Files\Photo Viewer\resources\app.asar\node_modules\sharp\lib\sharp.js:30:9)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Program Files\Photo Viewer\resources\app.asar\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)

[确定]

-------------------
after install sharp，also error   -_-!

**Comment by Tenpi** [comment]
Delete `node_modules/sharp` and then install it again:

`npm install --platform=win32 --arch=x64 sharp`.

**Comment by brotherelric** [comment]
> Delete `node_modules/sharp` and then install it again:
> 
> `npm install --platform=win32 --arch=x64 sharp`.

how to? i can't do that on command prompt

**Comment by longware** [comment]
i install exe package, not source code
there is no node_modules dir
so this method can not resolve problem  :P

**Comment by Tenpi** [comment]
I might have to make this macOS-only since it doesn't seem like I can build for other platforms, but you are welcome to compile source code yourself until I can find a fix.

**Comment by longware** [comment]
Thank you, your project is great！

**Comment by brotherelric** [comment]
rip windows ver.
